### ISSUE TITLE
Add common CI tasks

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/uds-marketplace#93]
Some GitHub jobs do not work on private repositories, add once repository is public.

dependency-review.yaml
```
name: Dependency Review
on: pull_request

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Dependency Review
        uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
```

scan-codeql.yaml
```
name: Analyze CodeQL

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
      - "goreleaser.yml"
  schedule:
    - cron: "32 2 * * 5"

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["typescript"]
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@2d790406f505036ef40ecba973cc774a50395aac # v3.25.13
        env:
          CODEQL_EXTRACTOR_GO_BUILD_TRACING: on
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql.yaml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@2d790406f505036ef40ecba973cc774a50395aac # v3.25.13
        with:
          category: "/language:${{matrix.language}}"
```
